# Name of the pipeline
name: Run HCL OneTest Suite
 
# Trigger pipeline when changes are made to the main branch
trigger:
  branches:
    include:
      - main
 
# Define the pool with the agent where you want to run the pipeline
pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest' based on your agent's OS
 
# Define pipeline stages
stages:
  - stage: Test
    jobs:
      - job: RunTests
        displayName: "Run HCL OneTest Tests"
        steps:
          # 1. Checkout the code
          - task: Checkout@1
            displayName: 'Checkout Code'
 
          # 2. Install .NET SDK if required (adjust based on your test requirements)
          - task: UseDotNet@2
            displayName: 'Install DotNet SDK'
            inputs:
              packageType: 'sdk'
              version: '5.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet
 
          # 3. Execute HCL OneTest Suite with the updated extension
          - task: HCL DevOps Test Workbench@1
            displayName: 'Run HCL OneTest Suite'
            inputs:
              serverUrl: '$(OneTestHub)'  # URL for HCL OneTest Server
              testSuiteId: '$(testSuiteId)'        # The ID of the test suite
              projectArea: '$(projectArea)'        # Name of the project area
              credentialsType: 'basic'
              userName: '$(username)'              # Set as pipeline secret/variable
              password: '$(password)'              # Set as pipeline secret/variable
              environment: '$(environmentName)'    # The environment in which to run the tests
              testSuiteTags: '$(tags)'             # Any tags for filtering tests (Optional)
              publishResults: true                 # To publish test results in Azure
 
          # 4. Publish Test Results
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFiles: '**/*.trx'        # File generated by HCL OneTest
              testRunTitle: 'HCL OneTest Results'
              failTaskOnFailedTests: true
