# Name of the pipeline
name: Run HCL OneTest Suite and WebUI Tests
 
# Trigger pipeline when changes are made to the main branch
trigger:
  branches:
    include:
      - main
 
# Define the pool with the agent where you want to run the pipeline
pool:
  vmImage: 'ubuntu-latest'  # or 'windows-latest' based on your agent's OS
 
# Define pipeline stages
stages:
  - stage: Test
    jobs:
      - job: RunTests
        displayName: "Run HCL OneTest Suite and WebUI Tests"
        steps:
          # 1. Checkout the code
          - task: Checkout@1
            displayName: 'Checkout Code'
 
          # 2. Install .NET SDK if required (adjust based on your test requirements)
          - task: UseDotNet@2
            displayName: 'Install DotNet SDK'
            inputs:
              packageType: 'sdk'
              version: '5.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet
 
          # 3. Execute HCL OneTest Suite using HCL DevOps Test Workbench extension
          - task: HCLTechnologies.build-release-task-hcl.onetestui.HCLOneTestUITask@2
            displayName: 'Run HCL OneTest Suite'
            inputs:
              serverUrl: '$(hclOneTestServerUrl)'  # URL for HCL OneTest Server
              testSuiteId: '$(testSuiteId)'        # The ID of the test suite
              projectArea: '$(projectArea)'        # Name of the project area
              credentialsType: 'basic'
              userName: '$(username)'              # Set as pipeline secret/variable
              password: '$(password)'              # Set as pipeline secret/variable
              environment: '$(environmentName)'    # The environment in which to run the tests
              testSuiteTags: '$(tags)'             # Any tags for filtering tests (Optional)
              publishResults: true                 # To publish test results in Azure

          # 4. Run WebUI Test after the integration
          - task: HCLTechnologies.build-release-task-hcl.onetestui.HCLOneTestUITask@2
            displayName: 'Run HCL WebUI Tests'
            inputs:
              serverUrl: '$(hclOneTestServerUrl)'  # URL for HCL OneTest Server
              testSuiteId: '$(webUITestSuiteId)'   # The ID for the WebUI test suite
              projectArea: '$(projectArea)'        # Project area for WebUI tests
              credentialsType: 'basic'
              userName: '$(username)'              # Set as pipeline secret/variable
              password: '$(password)'              # Set as pipeline secret/variable
              environment: '$(webUIEnvironment)'   # Environment for WebUI tests
              testSuiteTags: '$(webUITags)'        # Tags for WebUI tests (Optional)
              publishResults: true                 # To publish WebUI test results

          # 5. Publish Test Results for WebUI
          - task: PublishTestResults@2
            displayName: 'Publish WebUI Test Results'
            inputs:
              testResultsFiles: '**/*.trx'        # File generated by WebUI tests
              testRunTitle: 'HCL WebUI Test Results'
              failTaskOnFailedTests: true
